name: Deploy to AWS ECS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: node-devops-app
  ECS_CLUSTER: node-cluster
  ECS_SERVICE: node-service

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AKIATUVUMMLZ3USECCCY }}
        aws-secret-access-key: ${{ secrets.QIkMFVlzhh852m+6W1dq+ShzCoLlDwv6DVHLtsM7 }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Docker Image
      run: docker build -t $ECR_REPOSITORY .

    - name: Tag Image
      run: |
        docker tag $ECR_REPOSITORY:latest \
        ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest

    - name: Push to ECR
      run: |
        docker push \
        ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest

    - name: Deploy to ECS
      run: |
        aws ecs update-service \
          --cluster $ECS_CLUSTER \
          --service $ECS_SERVICE \
          --force-new-deployment
